# Generated by Django 5.2.6 on 2025-10-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "group_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="分组名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "分组",
                "verbose_name_plural": "分组",
                "db_table": "group",
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                ("major_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "major_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="专业名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "专业",
                "verbose_name_plural": "专业",
                "db_table": "major",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("stu_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "stu_no",
                    models.CharField(max_length=50, unique=True, verbose_name="学号"),
                ),
                ("stu_name", models.CharField(max_length=255, verbose_name="姓名")),
                ("grade", models.CharField(max_length=50, verbose_name="年级")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "is_gleader",
                    models.BooleanField(default=False, verbose_name="是否为组长"),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="studentapp.group",
                        verbose_name="分组",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="studentapp.major",
                        verbose_name="专业",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "db_table": "student",
            },
        ),
    ]
