# Generated by Django 5.2.6 on 2025-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_no', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('teacher_name', models.CharField(max_length=255, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='电子邮箱')),
                ('research_direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='研究方向')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher',
            },
        ),
    ]
