# Generated by Django 5.2.6 on 2025-09-21 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='团队名称')),
                ('description', models.TextField(blank=True, verbose_name='团队描述')),
                ('project_title', models.CharField(blank=True, max_length=200, verbose_name='项目标题')),
                ('project_description', models.TextField(blank=True, verbose_name='项目描述')),
                ('max_members', models.PositiveIntegerField(default=4, verbose_name='最大成员数')),
                ('status', models.CharField(choices=[('forming', '组建中'), ('complete', '已完成'), ('disbanded', '已解散')], default='forming', max_length=10, verbose_name='团队状态')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='队长')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
                'db_table': 'teams_team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('left', '已退出')], default='pending', max_length=10, verbose_name='状态')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='团队角色')),
                ('application_message', models.TextField(blank=True, verbose_name='申请信息')),
                ('response_message', models.TextField(blank=True, verbose_name='回复信息')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team', verbose_name='团队')),
            ],
            options={
                'verbose_name': '团队成员资格',
                'verbose_name_plural': '团队成员资格',
                'db_table': 'teams_membership',
                'ordering': ['-applied_at'],
                'unique_together': {('team', 'student')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='teams.TeamMembership', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='邀请信息')),
                ('status', models.CharField(choices=[('pending', '待回应'), ('accepted', '已接受'), ('declined', '已拒绝'), ('expired', '已过期')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回应时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='被邀请人')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team', verbose_name='团队')),
            ],
            options={
                'verbose_name': '团队邀请',
                'verbose_name_plural': '团队邀请',
                'db_table': 'teams_invitation',
                'ordering': ['-created_at'],
                'unique_together': {('team', 'invitee')},
            },
        ),
    ]
