# Generated by Django 5.2.6 on 2025-09-21 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='选择周期名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('student_selection_start', models.DateTimeField(verbose_name='学生选择开始时间')),
                ('student_selection_end', models.DateTimeField(verbose_name='学生选择结束时间')),
                ('teacher_selection_start', models.DateTimeField(verbose_name='导师选择开始时间')),
                ('teacher_selection_end', models.DateTimeField(verbose_name='导师选择结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '选择周期',
                'verbose_name_plural': '选择周期',
                'db_table': 'selections_selection_period',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('individual', '个人'), ('team', '团队')], max_length=10, verbose_name='选择类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='优先级')),
                ('application_message', models.TextField(blank=True, verbose_name='申请信息')),
                ('response_message', models.TextField(blank=True, verbose_name='回复信息')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_selections', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to=settings.AUTH_USER_MODEL, verbose_name='导师')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_selections', to='teams.team', verbose_name='团队')),
            ],
            options={
                'verbose_name': '导师选择',
                'verbose_name_plural': '导师选择',
                'db_table': 'selections_mentor_selection',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', '感兴趣'), ('selected', '已选择'), ('rejected', '已拒绝')], default='interested', max_length=10, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_selections', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student_selections', to=settings.AUTH_USER_MODEL, verbose_name='导师')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_selections', to='teams.team', verbose_name='团队')),
            ],
            options={
                'verbose_name': '导师选择学生',
                'verbose_name_plural': '导师选择学生',
                'db_table': 'selections_teacher_selection',
                'ordering': ['-created_at'],
            },
        ),
    ]
