# Generated by Django 5.2.6 on 2025-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentapp', '0001_initial'),
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=150, unique=True)),
                ('admin_username', models.CharField(max_length=150, unique=True)),
                ('admin_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MutualSelectionEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, verbose_name='分组名称')),
                ('stu_start_time', models.DateTimeField(verbose_name='学生开始时间')),
                ('stu_end_time', models.DateTimeField(verbose_name='学生截止时间')),
                ('tea_start_time', models.DateTimeField(verbose_name='教师开始时间')),
                ('tea_end_time', models.DateTimeField(verbose_name='教师截止时间')),
                ('teacher_choice_limit', models.PositiveIntegerField(default=5, help_text='每个导师在此活动中最多可以选择的小组数量', verbose_name='教师可选小组数')),
                ('students', models.ManyToManyField(related_name='mutual_selection_events', to='studentapp.student', verbose_name='参与学生')),
                ('teachers', models.ManyToManyField(related_name='mutual_selection_events', to='teacherapp.teacher', verbose_name='参与教师')),
            ],
            options={
                'verbose_name': '毕业设置分组配置',
                'verbose_name_plural': '毕业设置分组配置',
                'db_table': 'mutual_selection_event',
            },
        ),
    ]
