# Generated by Django 5.2.6 on 2025-10-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(max_length=150, unique=True)),
                ("admin_username", models.CharField(max_length=150, unique=True)),
                ("admin_password", models.CharField(max_length=128)),
            ],
        ),
    ]
