# Generated by Django 5.2.6 on 2025-11-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('studentapp', '0001_initial'),
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, verbose_name='分组名称')),
                ('project_title', models.CharField(blank=True, max_length=255, verbose_name='项目标题')),
                ('project_description', models.TextField(blank=True, verbose_name='项目简介')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_groups', to='teacherapp.teacher', verbose_name='最终指导老师')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='studentapp.student', verbose_name='队长')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='adminapp.mutualselectionevent', verbose_name='所属互选活动')),
                ('preferred_advisor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_as_first', to='teacherapp.teacher', verbose_name='第一志愿导师')),
                ('preferred_advisor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_as_second', to='teacherapp.teacher', verbose_name='第二志愿导师')),
                ('preferred_advisor_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_as_third', to='teacherapp.teacher', verbose_name='第三志愿导师')),
            ],
            options={
                'verbose_name': '团队/分组',
                'verbose_name_plural': '团队/分组',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teamapp.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studentapp.student')),
            ],
            options={
                'verbose_name': '团队成员关系',
                'verbose_name_plural': '团队成员关系',
                'db_table': 'team_membership',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member_of_groups', through='teamapp.GroupMembership', to='studentapp.student', verbose_name='团队成员'),
        ),
        migrations.CreateModel(
            name='ProvisionalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('auto', '自动分配'), ('manual', '手动调整')], default='auto', max_length=10)),
                ('score', models.FloatField(default=0, help_text='匹配得分')),
                ('explanation', models.CharField(blank=True, help_text='匹配原因说明', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_assignments', to='adminapp.mutualselectionevent')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_assignment', to='teamapp.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_assignments', to='teacherapp.teacher')),
            ],
            options={
                'verbose_name': '临时分配结果',
                'verbose_name_plural': '临时分配结果',
                'db_table': 'provisional_assignment',
            },
        ),
        migrations.CreateModel(
            name='TeacherGroupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_rank', models.PositiveIntegerField(verbose_name='志愿顺序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preferences', to='teamapp.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_preferences', to='teacherapp.teacher')),
            ],
            options={
                'verbose_name': '教师组队志愿',
                'verbose_name_plural': '教师组队志愿',
                'db_table': 'teacher_group_preference',
            },
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['student', 'group'], name='team_member_student_b85b69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('student', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('event', 'group_name')},
        ),
        migrations.AlterUniqueTogether(
            name='provisionalassignment',
            unique_together={('event', 'group')},
        ),
        migrations.AddIndex(
            model_name='teachergrouppreference',
            index=models.Index(fields=['teacher', 'preference_rank'], name='teacher_gro_teacher_c79c03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachergrouppreference',
            unique_together={('teacher', 'group')},
        ),
    ]
